services:
  springboot:
    build: .
    container_name: student-api
    restart: on-failure
    ports:
      - "8300:8300"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/studentclass_new?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: